PFIN-68 - Enhancements for ISS Interface v1.0.3 - new EMV tags
infraxis/PFINServiceProviders pull request #5
Opened 2021-01-07 12:41 UTC by fsemerdzhieva

added some additional checks+emv response data, merchantId and check for track2 length

2021-01-07 12:52 UTC, dianavicol requested changes
Looks good. Just some teeny-tiny points

2021-01-07 12:52 UTC, dianavicol commented on ISS/develop/scripts/Build Request Message.js
> +    //log.debug(getPrettyJsonString(obj));
Could you delete this?

2021-01-07 12:52 UTC, dianavicol commented on ISS/develop/scripts/Build Request Message.js
> +    }
And this

2021-01-07 12:52 UTC, dianavicol commented on ISS/develop/scripts/Process Response Message.js
> +        log.write("EMV");
Could you provide more details is this log, like _Processing EMV Response_

2021-01-07 12:53 UTC, dianavicol commented on ISS/develop/scripts/Process Response Message.js
> +        log.write("EMV");
and maybe remove the ToDo comment

2021-01-07 12:59 UTC, fsemerdzhieva commented on ISS/develop/scripts/Process Response Message.js
> +        log.write("EMV");
Yeah this was debug comment I forgot to delete

2021-01-08 09:56 UTC, dianavicol approved these changes
👍

2021-01-08 09:57 UTC, merged